export const VIDEO_STREAMING_URL = "VIDEO_LIVESTREAM_URL";
export const VIDEO_STREAMING_VISIBILITY = "VIDEO_STREAMING_VISIBILITY";

export const AUDIO_STREAMING_URL = "AUDIO_LIVESTREAM_URL";
export const AUDIO_STREAMING_VISIBILITY = "AUDIO_STREAMING_VISIBILITY";
